/**
 * Blog topics — the curated set of SEO articles the content engine generates.
 * Each targets a real, high-intent search query and links to relevant /analysis
 * pages (internal linking + a funnel into the product). Content is generated by
 * Claude and cached; these entries define WHAT to write and which tickers to
 * cross-link (kept deterministic here rather than trusting the model).
 */

import type { AssetId } from '@/lib/data/types';

export interface BlogTopic {
  slug: string;
  title: string;
  /** Primary keyword/intent — steers the generation prompt. */
  keyword: string;
  category: 'Comparisons' | 'Investing Basics' | 'Stock Questions' | 'Guides';
  /** Assets to cross-link to their /analysis pages. */
  related: AssetId[];
}

export const BLOG_TOPICS: BlogTopic[] = [
  // ── Comparisons (high search volume) ──
  { slug: 'nvidia-vs-amd',      title: 'Nvidia vs AMD: Which AI Chip Stock Is Better to Research?', keyword: 'Nvidia vs AMD stock', category: 'Comparisons', related: ['NASDAQ:NVDA', 'NASDAQ:AMD'] },
  { slug: 'apple-vs-microsoft', title: 'Apple vs Microsoft: Comparing the Two Biggest Tech Stocks', keyword: 'Apple vs Microsoft stock', category: 'Comparisons', related: ['NASDAQ:AAPL', 'NASDAQ:MSFT'] },
  { slug: 'visa-vs-mastercard', title: 'Visa vs Mastercard: Comparing the Payment Giants', keyword: 'Visa vs Mastercard stock', category: 'Comparisons', related: ['NYSE:V', 'NYSE:MA'] },
  { slug: 'alphabet-vs-meta',   title: 'Alphabet vs Meta: Which Ad Giant to Research?', keyword: 'Google vs Meta stock', category: 'Comparisons', related: ['NASDAQ:GOOGL', 'NASDAQ:META'] },
  { slug: 'tesla-vs-toyota',    title: 'Tesla vs Toyota: EV Disruptor vs Auto Titan', keyword: 'Tesla vs Toyota stock', category: 'Comparisons', related: ['NASDAQ:TSLA', 'NYSE:TM'] },

  // ── Investing basics (evergreen, huge search) ──
  { slug: 'how-to-analyze-a-stock', title: 'How to Analyze a Stock: A Beginner’s Framework', keyword: 'how to analyze a stock', category: 'Guides', related: ['NASDAQ:AAPL'] },
  { slug: 'what-is-pe-ratio',       title: 'What Is the P/E Ratio and How to Use It', keyword: 'what is P/E ratio', category: 'Investing Basics', related: ['NASDAQ:AAPL', 'NASDAQ:NVDA'] },
  { slug: 'what-is-ebitda',         title: 'What Is EBITDA? A Simple Explanation', keyword: 'what is EBITDA', category: 'Investing Basics', related: [] },
  { slug: 'how-to-read-a-balance-sheet', title: 'How to Read a Balance Sheet', keyword: 'how to read a balance sheet', category: 'Investing Basics', related: [] },
  { slug: 'what-is-market-cap',     title: 'What Is Market Cap and Why It Matters', keyword: 'what is market cap', category: 'Investing Basics', related: ['NASDAQ:AAPL'] },
  { slug: 'how-to-value-a-stock',   title: 'How to Value a Stock: DCF, Multiples and More', keyword: 'how to value a stock', category: 'Guides', related: [] },
  { slug: 'bull-case-vs-bear-case', title: 'Bull Case vs Bear Case: How to Weigh Both Sides', keyword: 'bull case vs bear case', category: 'Guides', related: ['NASDAQ:TSLA'] },

  // ── Stock questions (high intent) ──
  { slug: 'is-nvidia-overvalued',   title: 'Is Nvidia Overvalued? How to Think About It', keyword: 'is Nvidia overvalued', category: 'Stock Questions', related: ['NASDAQ:NVDA', 'NASDAQ:AMD'] },
  { slug: 'is-tesla-a-good-stock',  title: 'Is Tesla a Good Stock to Research?', keyword: 'is Tesla a good stock', category: 'Stock Questions', related: ['NASDAQ:TSLA'] },
  { slug: 'most-researched-ai-stocks', title: 'The Most-Researched AI Stocks Right Now', keyword: 'best AI stocks', category: 'Stock Questions', related: ['NASDAQ:NVDA', 'NASDAQ:AMD', 'NASDAQ:MSFT', 'NASDAQ:TSM', 'NASDAQ:ARM'] },
  { slug: 'how-to-spot-undervalued-stocks', title: 'How to Spot Undervalued Stocks', keyword: 'how to find undervalued stocks', category: 'Guides', related: [] },
  { slug: 'understanding-dividend-stocks', title: 'Understanding Dividend Stocks: What to Look For', keyword: 'dividend stocks explained', category: 'Investing Basics', related: ['NYSE:KO', 'NYSE:PG', 'NYSE:JNJ'] },
  { slug: 'how-ai-analyzes-stocks', title: 'How AI Analyzes Stocks (and Where It Falls Short)', keyword: 'AI stock analysis', category: 'Guides', related: ['NASDAQ:NVDA'] },
];

export function findTopic(slug: string): BlogTopic | undefined {
  return BLOG_TOPICS.find((t) => t.slug === slug);
}

export function groupedTopics(): Array<{ category: string; topics: BlogTopic[] }> {
  const order: string[] = [];
  const map = new Map<string, BlogTopic[]>();
  for (const t of BLOG_TOPICS) {
    if (!map.has(t.category)) { map.set(t.category, []); order.push(t.category); }
    map.get(t.category)!.push(t);
  }
  return order.map((category) => ({ category, topics: map.get(category)! }));
}
