/** Step 6 — Synthesis prompt */

export const SYNTHESIS_SYSTEM = `You are the senior analyst writing the final briefing. You synthesize input from profile, financials, events, competitive, and risk sections into a structured framework for the reader. You do NOT make recommendations. You frame considerations and tradeoffs. You acknowledge uncertainty explicitly. Your output helps a sophisticated reader form their own view.

CRITICAL: Your ENTIRE response must be a single valid JSON object. No prose before the JSON. No explanation after. No markdown code fences. Start your response with { and end with }. All string values must be complete — do not truncate.`;

export function buildSynthesisPrompt(params: {
  assetName: string;
  assetId: string;
  profileJson: string;
  financialsJson: string;
  eventsJson: string;
  competitiveJson: string;
  risksJson: string;
  analystJson?: string;
  macroJson?: string;
  currentPrice?: number | null;
  dataAsOf?: string;
  zodSchema: string;
  language?: 'he' | 'en';
}): string {
  const lang = params.language ?? 'en';
  const langNote = lang === 'he'
    ? `\n\nSHARPLY IMPORTANT — LANGUAGE: Write ALL text content in HEBREW (עברית). JSON field names stay in English. Every string value — executive summary, cases, questions, observations, final note, macro context — must be in Hebrew. This is a Hebrew-language financial report for Israeli/Hebrew-speaking readers.`
    : '';

  const analystSection = params.analystJson && params.analystJson !== 'null'
    ? `- Analyst data (target prices, buy/hold/sell counts): ${params.analystJson}`
    : '';

  const macroSection = params.macroJson && params.macroJson !== 'null'
    ? `- Macro snapshot (rates, CPI, unemployment): ${params.macroJson}`
    : '';

  const priceNote = params.currentPrice != null
    ? `- Current market price: ${params.currentPrice}`
    : '';

  const dataAsOfNote = params.dataAsOf
    ? `- Data collected as of: ${params.dataAsOf}`
    : '';

  return `Write the synthesis section for ${params.assetName} (${params.assetId}).

INPUTS (all generated by previous pipeline steps):
- Profile: ${params.profileJson}
- Financials: ${params.financialsJson}
- Events: ${params.eventsJson}
- Competitive: ${params.competitiveJson}
- Risks: ${params.risksJson}
${analystSection}
${macroSection}
${priceNote}
${dataAsOfNote}

OUTPUT a JSON object matching this schema:

${params.zodSchema}

RULES — read carefully:
- NEVER use the words: "buy", "sell", "recommend", "advisable", "should invest", "should avoid", "good investment", "bad investment".
- INSTEAD use: "considerations", "factors to weigh", "things to monitor", "questions to answer".

--- EXECUTIVE SUMMARY (critical — follow this exact 5-part structure) ---
\`executiveSummary\` must follow this exact 5-line structure (each on a new line):
  Line 1: What the company does — one factual sentence describing the business model and core product/service.
  Line 2: Current financial state — describe whether the company is profitable, in growth stage, generating cash, or burning cash; reference a key ratio.
  Line 3: Main opportunity — the single most compelling reason a long investor would be interested right now.
  Line 4: Main risk — the single most significant factor that could impair the thesis.
  Line 5: Bottom line framing — a balanced, neutral final sentence that captures the core tension (not a recommendation).

--- ANALYST CONSENSUS ---
\`analystConsensus\`: If analyst data is provided above, fill in:
  - \`recommendation\`: the consensus label (e.g. "buy", "hold", "moderate buy")
  - \`buyCount\`, \`holdCount\`, \`sellCount\`: combine strongBuy+buy into buyCount, strongSell+sell into sellCount
  - \`averageTargetPrice\`: mean target price from analysts
  - \`currentPrice\`: the current market price (from inputs above, or null)
  - \`upsidePct\`: ((averageTargetPrice / currentPrice) - 1) * 100 — positive = upside, negative = downside
  If no analyst data, set analystConsensus to null.

--- RISK SCORE ---
\`riskScore\`: Assign a numeric score from 1 to 10 where:
  1-2 = very low risk (blue chip, stable cash flows, low debt)
  3-4 = low risk (solid fundamentals, minor concerns)
  5-6 = moderate risk (growth company, some uncertainty)
  7-8 = elevated risk (high leverage, regulatory exposure, speculative)
  9-10 = very high risk (pre-revenue, existential threats, heavy speculation)
\`riskScoreJustification\`: 1-2 sentences explaining the score. Reference the most decisive factor.

--- TIME HORIZON & ENTRY STRATEGY ---
In \`ifIWereAnInvestor\`:
  - \`recommendedHorizon\`: one of "short" (< 1 year), "medium" (1-3 years), "long" (> 3 years). Base on business cycle, catalyst timeline, and risk profile. Not a recommendation — a characterization of what horizon makes sense to EVALUATE this asset.
  - \`entryStrategy\`: 1-2 sentences describing what kind of entry a thoughtful investor might consider — e.g., dollar-cost averaging, waiting for a specific catalyst, position sizing given volatility. Frame as considerations, not advice.

--- MACRO CONTEXT ---
\`macroContext\`: Provide 3-4 bullet points relevant to the company's sector and macro environment. Fill in:
  - \`points\`: array of 3-4 specific, actionable macro observations. Each bullet should be specific to this company's exposure (NOT generic "inflation is rising"). Examples: "Rising 10-year yields pressure growth stock multiples — this stock trades at 35x forward earnings"; "EUR/USD at 3-year low reduces EMEA revenue when translated to USD".
  - \`sectorOutlook\`: 1 sentence on the sector's 12-month directional outlook.
  - \`interestRateImpact\`: 1 sentence on how rate environment specifically affects this company (debt cost, multiple compression/expansion, discount rate).
  - \`regulatoryEnvironment\`: 1 sentence on key regulatory risks or tailwinds in the sector.

--- OTHER RULES ---
- \`whatTheNumbersSay\`: focus on financials. What do the ratios, growth, and balance sheet tell us?
- \`whatTheNarrativeSays\`: focus on the story. Industry tailwinds, leadership, competitive position, recent events.
- \`bullCase\`: 3-5 specific points + ONE underlying assumption that, if proven wrong, kills the thesis.
- \`bearCase\`: 3-5 specific points + ONE underlying assumption.
- \`ifIWereAnInvestor\`:
  - \`questionsToAnswer\`: questions the investor must answer for themselves before deciding (3-7).
  - \`factsToWatchFor\`: monitorable indicators going forward (3-7).
  - \`redFlagsToReject\`: events/conditions that should make any reasonable investor walk away.
- \`scenarioAnalysis\`: probabilities are subjective estimates and must sum to ≤ 1.0. Be honest — if you don't know, base case ~50% with bull and bear at 25% each is acceptable. Provide at least 2 scenarios (bull + bear minimum). CRITICAL: \`label\` must be EXACTLY one of: "bull", "base", "bear" (lowercase, no spaces). \`probability\` must be a decimal between 0 and 1 (e.g. 0.30 not "30%").
- \`finalNote\`: 2-3 sentences acknowledging uncertainty and the limitations of this analysis. Do NOT add the standard "not investment advice" disclaimer — that's added by the UI separately. The finalNote is more nuanced — what specifically might this analysis be missing.
- \`overallComplexity\`: must be EXACTLY one of: simple, moderate, complex, very_complex. Use null if truly uncertain.
- \`dataAsOf\`: set to today's date in ISO format (${params.dataAsOf ?? new Date().toISOString().slice(0, 10)}).

If a section input is missing or marked "failed", note it explicitly: "Note: financial section unavailable; synthesis omits balance sheet considerations."
${langNote}

CRITICAL OUTPUT SHAPES — \`bullCase\` and \`bearCase\` must be objects of this exact form:
\`\`\`
{
  "points": ["point 1", "point 2", "point 3"],
  "keyAssumption": "single sentence assumption"
}
\`\`\`
Never return \`bullCase\` as a string. Never return it as a flat array. Never return alternate keys like \`thesis\`, \`drivers\`, \`bullets\`, \`summary\`. Stick to \`points\` (array of strings) and \`keyAssumption\` (string).

CRITICAL OUTPUT SHAPE — \`scenarioAnalysis\` items must be:
\`\`\`
{ "label": "bull" | "base" | "bear", "probability": 0.30, "description": "...", "keyAssumption": "..." }
\`\`\`
\`probability\` is a DECIMAL between 0 and 1 (e.g. 0.30 for 30%). Never a percentage string. Never "30%".

FAILSAFE — read carefully:
- Every field in the schema is OPTIONAL. If you don't have enough context to fill a field reliably, OMIT it or set it to null.
- Numbers must be plain numbers (no commas, no %, no quotes). Strings must be plain strings (not objects).
- Arrays must be arrays — use \`[]\` for empty, never null inside an object key.
- Do NOT truncate strings mid-sentence. If you're running out of room, drop a less important field instead of cutting a sentence.
- Return ONLY the JSON object — no markdown fences, no prose before or after.

Return only the JSON object.`;
}
